<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRLFQ5jK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRLFQ5jK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRLFQ5jK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRLFQ5jK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRLFQ5jK\App_KernelDevDebugContainer([
    'container.build_hash' => 'RLFQ5jK',
    'container.build_id' => 'f5d0dfd8',
    'container.build_time' => 1669283221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRLFQ5jK');
