<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMbw38lW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMbw38lW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMbw38lW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMbw38lW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMbw38lW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mbw38lW',
    'container.build_id' => '4fc4e6dd',
    'container.build_time' => 1670256006,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMbw38lW');
