<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVcoZjx0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVcoZjx0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVcoZjx0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVcoZjx0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVcoZjx0\App_KernelDevDebugContainer([
    'container.build_hash' => 'VcoZjx0',
    'container.build_id' => '1d8c288b',
    'container.build_time' => 1669652479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVcoZjx0');
