<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_backgrounds' => [[], ['_controller' => 'App\\Controller\\BackgroundController::getBackgrounds'], [], [['text', '/api/backgrounds']], [], [], []],
    'api_background' => [['backgroundId'], ['_controller' => 'App\\Controller\\BackgroundController::getOneBackground'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'backgroundId', true], ['text', '/api/backgrounds']], [], [], []],
    'api_campaigns' => [[], ['_controller' => 'App\\Controller\\CampaignController::getCampaigns'], [], [['text', '/api/campaigns']], [], [], []],
    'api_campaign' => [['campaignId'], ['_controller' => 'App\\Controller\\CampaignController::getOneCampaing'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'campaignId', true], ['text', '/api/campaigns']], [], [], []],
    'api_classes' => [[], ['_controller' => 'App\\Controller\\CharacterClassController::getBackgrounds'], [], [['text', '/api/classes']], [], [], []],
    'api_character_class' => [['classId'], ['_controller' => 'App\\Controller\\CharacterClassController::getOneCharacter'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'classId', true], ['text', '/api/classes']], [], [], []],
    'api_characters' => [[], ['_controller' => 'App\\Controller\\CharacterController::getCharacters'], [], [['text', '/api/characters']], [], [], []],
    'api_character' => [['characterId'], ['_controller' => 'App\\Controller\\CharacterController::getOneCharacter'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'characterId', true], ['text', '/api/characters']], [], [], []],
    'api_faqs' => [[], ['_controller' => 'App\\Controller\\FAQController::getFaqs'], [], [['text', '/api/faqs']], [], [], []],
    'api_faq' => [['faqId'], ['_controller' => 'App\\Controller\\FAQController::getOneFaq'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'faqId', true], ['text', '/api/faqs']], [], [], []],
    'api_feedbacks' => [[], ['_controller' => 'App\\Controller\\FeedbackController::getFeedbacks'], [], [['text', '/api/feedbacks']], [], [], []],
    'api_feedback' => [['feedbackId'], ['_controller' => 'App\\Controller\\FeedbackController::getOneFeedback'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'feedbackId', true], ['text', '/api/feedbacks']], [], [], []],
    'api_notes' => [[], ['_controller' => 'App\\Controller\\NoteController::getNotes'], [], [['text', '/api/notes']], [], [], []],
    'api_note' => [['noteId'], ['_controller' => 'App\\Controller\\NoteController::getOneNote'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'noteId', true], ['text', '/api/notes']], [], [], []],
    'api_races' => [[], ['_controller' => 'App\\Controller\\RaceController::getRaces'], [], [['text', '/api/races']], [], [], []],
    'api_race' => [['raceId'], ['_controller' => 'App\\Controller\\RaceController::getOneCharacter'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'raceId', true], ['text', '/api/races']], [], [], []],
    'api_skills' => [[], ['_controller' => 'App\\Controller\\SkillController::getSkills'], [], [['text', '/api/skills']], [], [], []],
    'api_skill' => [['skillId'], ['_controller' => 'App\\Controller\\SkillController::getOneSkill'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'skillId', true], ['text', '/api/skills']], [], [], []],
    'api_spells' => [[], ['_controller' => 'App\\Controller\\SpellController::getSpells'], [], [['text', '/api/spells']], [], [], []],
    'api_spell' => [['spellId'], ['_controller' => 'App\\Controller\\SpellController::getOneSpell'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'spellId', true], ['text', '/api/spells']], [], [], []],
    'api_transformations' => [[], ['_controller' => 'App\\Controller\\TransformationController::getTransformations'], [], [['text', '/api/transformations']], [], [], []],
    'api_transformation' => [['transformationId'], ['_controller' => 'App\\Controller\\TransformationController::getOneTransformation'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'transformationId', true], ['text', '/api/transformations']], [], [], []],
    'api_users' => [[], ['_controller' => 'App\\Controller\\UserController::getUsers'], [], [['text', '/api/users']], [], [], []],
    'api_user' => [['userId'], ['_controller' => 'App\\Controller\\UserController::getOneUser'], ['id' => '\\d+'], [['variable', '/', '[^/]++', 'userId', true], ['text', '/api/users']], [], [], []],
    'api_user_characters' => [['userId'], ['_controller' => 'App\\Controller\\UserController::getCharactersOfOneUser'], ['id' => '\\d+'], [['text', '/characters'], ['variable', '/', '[^/]++', 'userId', true], ['text', '/api/users']], [], [], []],
    'api_user_active_character' => [['userId'], ['_controller' => 'App\\Controller\\UserController::getActiveCharacterOfOneUser'], ['id' => '\\d+'], [['text', '/activeCharacter'], ['variable', '/', '[^/]++', 'userId', true], ['text', '/api/users']], [], [], []],
];
